set_property SRC_FILE_INFO {cfile:E:/Code/4K-Upsampling-System-on-Zynq/subsystem_test/hdmi_test/hdmi_test.srcs/constrs_1/new/hdmi_cons.xdc rfile:../../../hdmi_test.srcs/constrs_1/new/hdmi_cons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E18   IOSTANDARD LVCMOS33 } [get_ports { hdmi_oen }]; #IO_L5P_T0_AD9P_35 Sch=hdmi_tx_hpd
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17   IOSTANDARD TMDS_33     } [get_ports { TMDS_clk_n }]; #IO_L13N_T2_MRCC_35 Sch=TMDS_data_clk_n
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H16   IOSTANDARD TMDS_33     } [get_ports { TMDS_clk_p }]; #IO_L13P_T2_MRCC_35 Sch=TMDS_data_clk_p
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D20   IOSTANDARD TMDS_33     } [get_ports { TMDS_data_n[0] }]; #IO_L4N_T0_35 Sch=TMDS_data_n[0]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D19   IOSTANDARD TMDS_33     } [get_ports { TMDS_data_p[0] }]; #IO_L4P_T0_35 Sch=TMDS_data_p[0]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B20   IOSTANDARD TMDS_33     } [get_ports { TMDS_data_n[1] }]; #IO_L1N_T0_AD0N_35 Sch=TMDS_data_n[1]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C20   IOSTANDARD TMDS_33     } [get_ports { TMDS_data_p[1] }]; #IO_L1P_T0_AD0P_35 Sch=TMDS_data_p[1]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A20   IOSTANDARD TMDS_33     } [get_ports { TMDS_data_n[2] }]; #IO_L2N_T0_AD8N_35 Sch=TMDS_data_n[2]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B19   IOSTANDARD TMDS_33     } [get_ports { TMDS_data_p[2] }]; #IO_L2P_T0_AD8P_35 Sch=TMDS_data_p[2]
